### ISSUE TITLE
We organized our first Local Meetup hosted by Cloud Native Westminster group London this is the request to add this as a Blog under the Blog section Request to add this as a Blog under the Blog section We organized our Local Meetup hosted by Cloud Native Westminster group London during TAG ENV’s CNCF Cloud Native Sustainability Week 2024

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [cncf/tag-env-sustainability#568] opened 2024-10-26 02:02 UTC
> ### GitHub tag of Blog Authors
> rohitg00, Santosh-Kumar-Perumal, VinodSRinCloud, MathewJoseph1993
> 
> ### GitHub tag of Blog Reviewers
> updated once people start reviewing the blog
> 
> ### GitHub tag of TAG ENV Lead that sponsors the blog
> updated once a TAG ENV lead assigned themselve
> 
> ### Abstract
> Greener first-ever Sustainability London Meetup with Sustainability Week 2024!
> 
> Organized by technology leaders Rohit Ghumare, Mathew Joseph, Vinod Sulochana Raveendran, Santosh Kumar Perumal, and Cloud Native Westminster, the event brought together distinguished speakers who shared insights on the intersection of technology and sustainability.
> 
> ### Scope
> https://docs.google.com/document/d/1DjLWBT6EBvtJSHAiBjouFquJ0pXNZAqWinhPaRkSecI/edit?usp=sharing
> 
> ### Goals and Non Goals
> https://docs.google.com/document/d/1DjLWBT6EBvtJSHAiBjouFquJ0pXNZAqWinhPaRkSecI/edit?usp=sharing
> 
> ### Todo items starting the blog post process
> * [x]  [Author] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.[x]  [Author] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.[ ]  [TAG ENV Lead] One of the TAG ENV leads assigned themselves to wrangle the blog[ ]  [TAG ENV Lead] Blog post outline and theme has been discussed[x]  [Author] Blog post written and ready for review
> 
> ### Todo items reviewing the blog post
> * [ ]  [Author] blog post PR opened (blog posts are added to the [`website/content/en/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/blog) folder for English content, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))[ ]  [Author] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.[ ]  [Author] Feedback and comments have been resolved.[ ]  [Reviewers] reviewed blog post.[ ]  [TAG ENV Lead] reviewed blog post.[ ]  [TAG ENV Lead] ready to get published.[ ]  [TAG ENV Lead] notified one of the ToC liaisons to sign off the blog post.[ ]  [OPTIONAL TAG ENV ToC Liaison] reviewed blog post.
> 
> ### Todo items reviewing the blog post
> * [ ]  [TAG ENV Lead] merged blog post.[ ]  [OPTIONAL TAG ENV Lead] schedule the blog post on the CNCF blog next to the TAG ENV blog[ ]  [Author] Wrote feedback about the blog post process as a comment under this issue
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct
> 
> ### Comments
> _No response_

# 🌍 CNCF Sustainability Week - London Meetup 2024 🌍

📅 **Date:** Thursday, October 24, 2024  
🕒 **Time:** 6:30 PM to 8:30 PM BST  
📍 **Location:** London Civo Tech Junction  

## 🚀 Cloud Native Westminster Meetup - A First for London! 🎉

We are thrilled to share the highlights from organizing the [first-ever Cloud Native Westminster meetup](https://community.cncf.io/events/details/cncf-cloud-native-westminster-presents-cncf-sustainability-week-2024-london-meetup/) in London during [TAG ENV’s CNCF Cloud Native Sustainability Week 2024](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/) 🌐. This event brought together passionate individuals from the tech community, all united by a shared commitment to promoting **sustainability through cloud-native and open-source practices**. Over the course of three hours, we hosted **four insightful talks** 🎙️ by leading sustainability experts and industry veterans, with plenty of time for **networking** 🤝 as well. A huge thanks to **Isovalent**, our amazing Venue Partner, for making it all possible! 🎊

---

## 🎉 Organizers and Host 🌟

- [Rohit Ghumare](https://www.linkedin.com/in/rohitghumare/) - Principal Product Evangelist at Taikun 
- [Mathew Joseph](https://www.linkedin.com/in/business-development-mathewjoseph/) - Strategic Partnerships and Alliances 
- [Vinod Sulochana Raveendran](https://www.linkedin.com/in/srvinod/) - Cloud Consultant at Tata Consultancy Services 
- [Santosh Kumar Perumal](https://www.linkedin.com/in/santosh-kumar-perumal/) - Cloud Consultant at Tata Consultancy Services 

<div align="center">
<Image src="https://github.com/user-attachments/assets/382ec17e-08a5-4522-a01e-f7d4608f066f" alt="Organizers and Host Image" width="300">
</div>

---

## 🎤 Talk 1: Sustainable Technology & the "3 Cs" 🌱

**Speaker:** *Subramanian Kuppuswami*  
**Title:** Global Sustainability Head, BFSI; Top 25 Sustainability Leaders 2024 👏  

<img src="https://github.com/user-attachments/assets/1a8a005e-0f43-4bf6-9d91-8b18f0b0cc9e" alt="Speaker Image" width="300" />

**Summary:**  
Subramanian's talk centered on the "3 Cs" of Cost, Carbon, and Cloud as pillars of sustainability in technology 🌍, highlighting both the opportunities and challenges posed by advancements in AI 🤖, Cloud ☁️, and Future Computing (such as Edge and Quantum computing). He shared an insightful analogy comparing the resource-conscious nature of film photography 📸 to today’s digital habits—where the ease of clicking countless photos masks the CO₂ footprint generated 🌿. This shift underscores the importance of awareness and sustainable design principles in technology.

The ICT industry accounts for 2.1–3.9% of global greenhouse emissions 🌎, with software's current carbon contribution lower than other sectors. However, this figure is anticipated to grow sharply due to AI, GenAI, and ongoing digital transformation. Subbi emphasized that organizations are now expanding their sustainability initiatives to address software’s energy impact at every lifecycle stage—from development through to operations 🔋. However, they face challenges due to a lack of detailed and transparent energy and carbon data 🔍.

**Conclusion:**  
Subbi posed a critical question: "Will moving to the cloud alone solve these challenges?" 🌩️ He urged for architectural solutions and innovations to engineer a sustainable future by tackling the deeper issues of energy efficiency, data transparency, and sustainable software practices 🔧💡.

---

## 🎤 Talk 2: Transforming Data Centers with eBPF ⚙️

**Speaker:** *Daniel Finneran*  
**Title:** Principal Community Advocate at Isovalent 🖥️  

<img src="https://github.com/user-attachments/assets/5c0ecaca-9405-49e9-a56f-cdf48b08efec" alt="Speaker Image" width="300" />

**Summary:**  
Daniel discussed the evolution of IT infrastructure and the industry's reliance on power-hungry devices within data centers worldwide 🌐. Over the past decade, data centers have made strides in energy efficiency ⚡ by consolidating workloads using virtualization, containerization, and Kubernetes 🚢. Now, the rise of eBPF (Extended Berkeley Packet Filter) is further transforming data center efficiency by reducing reliance on additional hardware devices 🔋. Dan explained how eBPF works and its applications in networking, observability, and security 🔍, highlighting that offloading processing to eBPF programs could significantly reduce the data center footprint 🌱.

He emphasized eBPF's potential to replace traditional hardware like load balancers, firewalls, TAP devices, and IDS (Intrusion Detection Systems) 🔒. As an open-source technology, eBPF allows for customization, meaning developers no longer have to wait for vendors to deliver solutions but can instead tailor tools to their own specifications. Dan also referenced KEPLER (Kubernetes-based Efficient Power Level Exporter), a cloud-native project leveraging eBPF to monitor energy usage within Kubernetes clusters, exemplifying how eBPF can drive energy-conscious computing ⚡🔋.

---

## 🎤 Talk 3: Optimizing Compute Density in Cloud ☁️

**Speaker:** *Charles Humble*  
**Title:** Freelance Techie, Podcaster 🎙️, Editor, Author 📚, and Consultant at Conissaaunce Limited  

<img src="https://github.com/user-attachments/assets/fac1de69-0801-4c4a-9096-445f577c251a" alt="Speaker Image" width="300" />

**Summary:**  
Charles emphasized the efficiency of high compute density in managed cloud services 💻, which allows shared resources across vast numbers of users to achieve optimal energy utilization 🔋. However, he noted that while many sustainability guides recommend shifting to the cloud 🌩️, it's crucial to consider green software principles for all environments 🌱. Charles provided practical advice on assessing current system efficiency, optimizing code and language choice 💻, and effectively communicating the value of green practices to leadership 🗣️.

He introduced energy proportionality, a concept from Google showing that even idle servers consume about half their power ⚡. To optimize energy use, Charles advised aiming for at least 50% machine utilization across all systems and eliminating “zombie” servers—unused machines still consuming resources 🧟‍♂️💻. He suggested regular audits and a “LightSwitchOps” approach, shutting off non-essential systems during low-demand hours 🕹️ for companies with localized or non-global operations.

**Recommendations:**  
Charles recommended optimizing workloads based on green energy availability 🌱, mentioning the real-time carbon intensity tool from Electricity Maps, which AWS, Google, and Salesforce use to help customers select eco-friendly energy sources 🌞. He encouraged organizations to publicly share their achievements through case studies, conferences, and articles to foster broader adoption of sustainable practices 📣, concluding with the key message: focus on operational efficiency as a first step in software sustainability, not just on the code itself 👨‍💻.

---

## 🎤 Talk 4: Sustainability Measurement Frameworks 📏

**Speaker:** *Dr. Swati Murthy*  
**Title:** Practice Director - Sustainability | Tata Consultancy Services | IRCA Certified ISO 50001 Auditor and Lead Energy Assessor 🌱  

**Summary:**  
Dr. Swati discussed the current limitations in sustainability measurement frameworks 📊, which often focus on enterprise-level ESG (Environment, Social, and Governance) goals 🌍 without industry-wide standards for impactful, cross-ecosystem sustainability outcomes 🌱. She introduced a proposal to embed sustainability throughout the design process by defining foundational elements, core principles, and key business imperatives for creating sustainable solutions.

A significant focus was on supply chain decarbonization as the "missing link" 🧩 in achieving net-zero targets ♻️, emphasizing the need to integrate sustainability from the ground up in supply chain management to drive meaningful environmental impact across industries 🌐🌍.

---
<div align="center">
<img src="https://github.com/user-attachments/assets/3033361c-64bd-453c-aa16-499cc476f532" alt="Meetup Image" width="300" />
</div>

Thank you to all the speakers, attendees, and organizers for making this Cloud Native Westminster meetup a success! Here’s to fostering more sustainable practices in technology together! 💡💚 🌍

**Comment by Santosh-Kumar-Perumal** [comment] 2024-10-26 02:33
Thanks @rohitg00 my bad I spend time to create the issue later realized you have already created one super fast always closing this please refer to the one @rohitg00  has created https://github.com/cncf/tag-env-sustainability/issues/567

**Comment by leonardpahlke** [comment] 2024-10-30 14:06
@claire-fletcher @Nancy-Chauhan @ams0 if you find time, could you take a look

**Comment by vallss** [comment] 2024-10-30 18:13
Closing this as duplicate of #567

**Closed by vallss** 2024-10-30 18:13 UTC
